version: "3"
services:
  web:
    image: goweb:1.0
    deploy:
      replicas: 3
      resources:
        limits: 
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "8001:8000"
    networks: 
      - gowebnet
networks: 
  gowebnet:
